### ISSUE TITLE
compile options

### ISSUE THREAD

**Issue by zhh710** [JCSDA/py-ncepbufr#14]
Hello，
I install it using 'python setup.py install' and meets error as follow:

gfortran -Wall -g -Wall -g -shared build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src/_bufrlibmodule.o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortranobject.o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src/_bufrlib-f2pywrappers.o -Lsrc -L/home/zhh/tools/anaconda2/lib -lbufr -lpython2.7 -lgfortran -o build/lib.linux-x86_64-2.7/_bufrlib.so
/opt/oscer/software/binutils/2.25-GCCcore-4.9.3/bin/ld.gold: error: build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src/_bufrlib-f2pywrappers.o: requires dynamic R_X86_64_PC32 reloc against 'adn30_' which may overflow at runtime; recompile with -fPIC
collect2: error: ld returned 1 exit status

I do not know how to add '-fPIC' option. Can anyone help?

**Comment by zhh710** [comment]
After 'setenv CFLAGS -fPIC; setenv FFLAGS -fPIC', I run 'python setup.py build' and 'python setup.py install' without errors.
But it gets 'ImportError' when I try to 'import ncepbufr' as follow:


`Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ncepbufr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhh/tools/anaconda2/lib/python2.7/site-packages/ncepbufr/__init__.py", line 1, in <module>
    import _bufrlib
ImportError: /home/zhh/tools/anaconda2/lib/python2.7/site-packages/_bufrlib.so: undefined symbol: __intel_sse2_strncpy
>>>
`
 
And I no not know what is the problem.

**Comment by jswhit** [comment]
Looks like maybe you built the bufr library with the intel compiler, but the shared object with the gfortran compiler?  I'd suggest building the lib with the same gfortran that distutils uses to build the shared object.

**Comment by zhh710** [comment]
>           Looks like maybe you built the bufr library with the intel compiler, but the shared object with the gfortran compiler?  I'd suggest building the lib with the same gfortran that distutils uses to build the shared object.

Hello,
Thanks for your time. I build bufr library with:
`setenv FC gfortran`
`setenv CC icc`

And I then build it using:
`python setup.py build config_fc --fcompiler=gfortran `

After this, I get:

`compiling Fortran sources`
`Fortran f77 compiler: ifort -Wall -g -ffixed-form -fno-second-underscore -xCORE-AVX2 -O3 -fPIC -O3 -funroll-loops`
`Fortran f90 compiler: /opt/oscer/software/GCCcore/4.9.3/bin/gfortran -Wall -g -fno-second-underscore -xCORE-AVX2 -O3 -fPIC -O3 -funroll-loops`
`Fortran fix compiler: /opt/oscer/software/GCCcore/4.9.3/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -xCORE-AVX2 -O3 -fPIC -O3 -funroll-loops`
`compile options: '-Ibuild/src.linux-x86_64-2.7 -I/home/zhh/tools/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/zhh/tools/anaconda2/include/python2.7 -c'`
`ifort:f77: build/src.linux-x86_64-2.7/src/_bufrlib-f2pywrappers.f`
**`ifort: command line warning #10157: ignoring option '-W'; argument is of wrong type`
`ifort: command line warning #10006: ignoring unknown option '-ffixed-form'`
`ifort: command line warning #10006: ignoring unknown option '-fno-second-underscore'`**
`/opt/oscer/software/GCCcore/4.9.3/bin/gfortran -Wall -g -Wall -g -shared build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src/_bufrlibmodule.o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/fortranobject.o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/src/_bufrlib-f2pywrappers.o -Lsrc -L/home/zhh/tools/anaconda2/lib -lbufr -lpython2.7 -lgfortran -o build/lib.linux-x86_64-2.7/_bufrlib.so`
`running build_scripts`
`creating build/scripts.linux-x86_64-2.7`

I got some warnings. I try to fix it by set F77=gfortran, but it does not work.

`gfortran:f77: build/src.linux-x86_64-2.7/src/_bufrlib-f2pywrappers.f`
`gfortran: error: language CORE-AVX2 not recognized`
`gfortran: error: language CORE-AVX2 not recognized`
`gfortran: error: language CORE-AVX2 not recognized`
`gfortran: error: language CORE-AVX2 not recognized`

Then I go back and set F77=ifort and go to next step:

`python setup.py install config_fc --fcompiler=gfortran`

I test the module with:
`python -m ncepbufr`

And I got this:

`Traceback (most recent call last):`
  `File "/home/zhh/tools/anaconda2/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)`
  `File "/home/zhh/tools/anaconda2/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package`
  `File "ncepbufr/__init__.py", line 1, in <module>`
    `import _bufrlib`
`ImportError: /home/zhh/tools/anaconda2/lib/python2.7/site-packages/_bufrlib.so: undefined symbol: __intel_sse2_strncpy`

It's confusing.

**Comment by jswhit** [comment]
It's still using ifort for some reason.  Try `python setup.py config_fc --help-fcompiler` to see what compilers are being detected.  You might need ` --fcompiler=gnu95`.

**Comment by zhh710** [comment]
Thank you.
It's resolved after I build the module with GNU compiler.

`module purge`

This comman clean the modules I load default by .bashrc, including Intel compiler.
