### ISSUE TITLE
BUFRLIB environment variables have recently switched to lower case

### ISSUE THREAD

**Issue by srherbener** [JCSDA/py-ncepbufr#28]
We recently changed BUFRLIB_ROOT and BUFRLIB_PATH environment variables to bufrlib_ROOT and bufrlib_PATH to fix an issue with CMake. It would be great to make the same changes in setup.py so that if the bufrlib library is loaded, the build process for ncepbufr would automatically find it and use it.

Thanks!

**Comment by jswhit2** [comment]
Fix for this in pull request #29
